### PR TITLE
Add support for getSupportedVoices() on iOS

### PR DESCRIPTION
**Pull request by gbj**
This is at least a quick fix for issue #37 which is working for my use case.

### CODE REVIEW

**Comment by robingenz** [comment]
Thank you for your contribution. I will review it in the next few days.

**Comment by robingenz** [comment]
Please always submit unrelated changes in separate pull requests.
I will test your first change soon.
For the second change I've found another fix which supports IETF BCP 47 language tag strings (see #66). 
So the second change should not be necessary anymore.

**Comment by gbj** [comment]
Sorry for that second commit — meant to commit it to my own local branch, not add it to the PR. My mistake!

**Comment by ecc521** [comment]
@robingenz Any chance we can get an update on this?

**Comment by robingenz** [comment]
@ecc521 This pr is waiting for the requested changes. Feel free to submit a new PR.

**Comment by ecc521** [comment]
@robingenz Done! #89

**Comment by gbj** [comment]
I'd completely forgotten this one even existed -- apologies and thanks for the new PR, @ecc521.

**Pull request closed without merging**
